### PR TITLE
Sync all locales from mojang/bedrock-samples

### PR DESCRIPTION
**Pull request by xxAROX**
It was very painful to scape the data via hands :G

### CODE REVIEW

**Comment by xxAROX** [comment]
Ahh i see the github web editor sucks with tabs

**Comment by IvanCraft623** [comment]
Can you keep the format? :P

**Comment by IvanCraft623** [comment]
You are including some languages that doesn't exists in Bedrock

**Comment by IvanCraft623** [comment]
You can see the list of Minecraft bedrock languages [here](https://github.com/Mojang/bedrock-samples/blob/main/resource_pack/texts/language_names.json)

**Comment by xxAROX** [comment]
ahh i forgot README.md

**Comment by xxAROX** [comment]
👍

**Comment by IvanCraft623** [comment]
Could you add a column in README with the names in English? Everything else looks good.

**Comment by IvanCraft623** [comment]
Thank you for your PR

**Comment by xxAROX** [comment]
No problem, i just want to contribute on open source projects for fun, to learn more time by time and making my bad English skills a bit better 😂

**Pull request merged**
